name: dagger
on:
  push:
    branches: [main]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get dpt
        run: curl -sLO https://github.com/TheFutonEng/dagger-dash-days/releases/download/v0.0.1/dagger-dash-days_v0.0.1_Linux_amd64 && chmod +x dagger-dash-days_v0.0.1_Linux_amd64
      - name: Package creation
        run: ./dagger-dash-days_v0.0.1_Linux_amd64 package create